# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - sim_scaled_joint_trajectory_controller

  sim_scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - sim_ur10e_shoulder_pan_joint
      - sim_ur10e_shoulder_lift_joint
      - sim_ur10e_elbow_joint
      - sim_ur10e_wrist_1_joint
      - sim_ur10e_wrist_2_joint
      - sim_ur10e_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true