controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    # Sadece temel controller'lar
    /sim/sim_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    /sim/sim_scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

# Joint State Broadcaster
/sim/sim_joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

# Scaled Joint Trajectory Controller
/sim/sim_scaled_joint_trajectory_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - sim_ur10e_shoulder_pan_joint
      - sim_ur10e_shoulder_lift_joint
      - sim_ur10e_elbow_joint
      - sim_ur10e_wrist_1_joint
      - sim_ur10e_wrist_2_joint
      - sim_ur10e_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    speed_scaling_interface_name: ""
    state_publish_rate: 50.0
    action_monitor_rate: 10.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0