# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - robot2_scaled_joint_trajectory_controller

  robot2_scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - robot2_ur10e_shoulder_pan_joint
      - robot2_ur10e_shoulder_lift_joint
      - robot2_ur10e_elbow_joint
      - robot2_ur10e_wrist_1_joint
      - robot2_ur10e_wrist_2_joint
      - robot2_ur10e_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true