/robot2/controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
        
    # Controller listesi
    robot2_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot2_io_and_status_controller:
      type: ur_controllers/GPIOController

    robot2_speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    robot2_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    robot2_scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    robot2_forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    robot2_forward_position_controller:
      type: position_controllers/JointGroupPositionController



# Speed Scaling State Broadcaster
/robot2/robot2_speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0

# Joint Trajectory Controller
/robot2/robot2_joint_trajectory_controller:
  ros__parameters:
    joints:
      - robot2_ur10e_shoulder_pan_joint
      - robot2_ur10e_shoulder_lift_joint
      - robot2_ur10e_elbow_joint
      - robot2_ur10e_wrist_1_joint
      - robot2_ur10e_wrist_2_joint
      - robot2_ur10e_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      robot2_ur10e_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      robot2_ur10e_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      robot2_ur10e_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      robot2_ur10e_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      robot2_ur10e_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      robot2_ur10e_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

# Scaled Joint Trajectory Controller
/robot2/robot2_scaled_joint_trajectory_controller:
  ros__parameters:
    type: ur_controllers/ScaledJointTrajectoryController
    joints:
      - robot2_ur10e_shoulder_pan_joint
      - robot2_ur10e_shoulder_lift_joint
      - robot2_ur10e_elbow_joint
      - robot2_ur10e_wrist_1_joint
      - robot2_ur10e_wrist_2_joint
      - robot2_ur10e_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    speed_scaling_interface_name: ""
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      robot2_ur10e_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      robot2_ur10e_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      robot2_ur10e_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      robot2_ur10e_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      robot2_ur10e_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      robot2_ur10e_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

# Forward Velocity Controller
/robot2/robot2_forward_velocity_controller:
  ros__parameters:
    joints:
      - robot2_ur10e_shoulder_pan_joint
      - robot2_ur10e_shoulder_lift_joint
      - robot2_ur10e_elbow_joint
      - robot2_ur10e_wrist_1_joint
      - robot2_ur10e_wrist_2_joint
      - robot2_ur10e_wrist_3_joint
    interface_name: velocity

# Forward Position Controller
/robot2/robot2_forward_position_controller:
  ros__parameters:
    joints:
      - robot2_ur10e_shoulder_pan_joint
      - robot2_ur10e_shoulder_lift_joint
      - robot2_ur10e_elbow_joint
      - robot2_ur10e_wrist_1_joint
      - robot2_ur10e_wrist_2_joint
      - robot2_ur10e_wrist_3_joint